Cars
MarynaNogtieva/train_project pull request #1
Opened 2017-10-03 13:27 UTC by MarynaNogtieva

Возможность управления вагонами (добавление/удаление/изменение)
 - При добавлении вагона указывается поезд, к которому он добавляется, а также:
 - Тип вагона (купейный/плацкартный)
 - Кол-во мест: верхних/нижних
При просмотре поезда, также должна отображаться следующая информация:
 - Кол-во плацкартный/купейных вагонов в составе поезда
 - Кол-во мест: плацкартных верхних/нижних, купейных верхних/нижних

2017-10-03 16:16 UTC, vkurennov requested changes

2017-10-03 16:16 UTC, vkurennov commented on app/views/trains/_train.html.erb
> +  <%econom_cars = train.cars.select {|car| car.is_econom}%>
Не нужно никаких подсчетов и алгоритмов писать в видах, все выносится в модели, а здесь просто вызываются нужные методы

2017-10-03 16:16 UTC, vkurennov commented on app/views/trains/show.html.erb
> +<%econom_cars = @train.cars.select {|car| car.is_econom}%>
Вот видишь, подсчет в видах ведет к дублированию. Если были бы методы моделей, дублирования бы не было.

2017-10-04 01:37 UTC, MarynaNogtieva commented on app/views/trains/_train.html.erb
> +  <%econom_cars = train.cars.select {|car| car.is_econom}%>
changes applied

2017-10-04 01:37 UTC, MarynaNogtieva commented on app/views/trains/show.html.erb
> +<%econom_cars = @train.cars.select {|car| car.is_econom}%>
yes, agree

2017-10-04 04:30 UTC, iBublik commented on app/models/car.rb
> +  validates :number, presence: true
Отделяй ассоциации и валидации пустой строкой - так читабельность выше. Вообще возьми за привычку логически разделять код на кусочки.

2017-10-04 04:30 UTC, iBublik commented on app/models/car.rb
> +
Лишние пустые строки убирай

2017-10-04 04:30 UTC, iBublik commented on app/models/train.rb
> +    business_cars = cars.select {|car| !car.is_econom}
Тут лучше использовать метод `reject`

2017-10-04 04:30 UTC, iBublik commented on db/migrate/20171002210652_create_cars.rb
> +      t.boolean :is_econom, default: true
Булево поле не самый удачный выбор в этой ситуации - с ним очень трудно расширять приложение. Представь, что добавится новый тип вагона (что весьма вероятно). Что в этом случае делать? Придется кучу кода переписывать. Так что отдавай предпочтение обычному текстовому полю, которое хранит тип вагона

2017-10-04 04:30 UTC, iBublik commented on app/views/cars/_form.html.erb
> +    <%= form.radio_button(:is_econom, true, :checked => true)%> Econom
При редактировании должен отмечаться реальный тип вагона, а сейчас всегда отмечается `Econom`

2017-10-04 10:58 UTC, vkurennov approved these changes

2017-10-06 02:29 UTC, MarynaNogtieva commented on db/migrate/20171002210652_create_cars.rb
> +      t.boolean :is_econom, default: true
changes applied, renamed is_econom to car_type and made it string type for database

2017-10-06 02:31 UTC, merged